[package]
name = "gxu-net-login"
version = "1.0.1"
edition = "2018"

[dependencies]
hyper = { version = "0.14.2", features = ["client", "tcp", "http1"] }
tokio = { version = "1.0.2", features = ["rt", "macros", "time"] }
itertools = "0.10.0"
anyhow = "1.0.38"
configparser = "2.0.0"
url = "2.2.0"
